### ISSUE TITLE
Wrong time imported for recurrent events after daylight savings time switch

### ISSUE THREAD

**Issue by eev2** [andrewramsay/ical_to_gcal_sync#20]
Hello. In my ical I have recurrent events. The time is imported correctly to Google calendar before the daylight savings time change (28 March in my case), but after that day the event is imported with one hour difference. If the ical is imported directly on Google calendar, then the correct time is shown. Also, if the event is not recurrent, and occurs after the daylight savings change, then it is imported with the correct time.

**Comment by andrewramsay** [comment]
Not sure why that's happening. This script shouldn't handle recurring events differently and they should come out of icalevents with the correct timezones already. 

I don't see the same problem with the ones I have in my feed. I have one for a Zoom meeting at 4pm every Friday and I can see it in GCal at the correct time through the 28th and on into April (same DST date as you). 

I also just tried creating a test event that recurs every month in the app generating my iCal feed. If I parse the feed with icalevents as in the script and print the start time and timezone it seems to be handling this correctly too, I can see the timezone offset going from 00:00 to +01:00 in April and back to 00:00 in November:
```
2021-03-11 15:00:00+00:00 tzfile('/usr/share/zoneinfo/Europe/London')
2021-04-11 15:00:00+01:00 tzfile('/usr/share/zoneinfo/Europe/London')
2021-05-11 15:00:00+01:00 tzfile('/usr/share/zoneinfo/Europe/London')
2021-06-11 15:00:00+01:00 tzfile('/usr/share/zoneinfo/Europe/London')
2021-07-11 15:00:00+01:00 tzfile('/usr/share/zoneinfo/Europe/London')
2021-08-11 15:00:00+01:00 tzfile('/usr/share/zoneinfo/Europe/London')
2021-09-11 15:00:00+01:00 tzfile('/usr/share/zoneinfo/Europe/London')
2021-10-11 15:00:00+01:00 tzfile('/usr/share/zoneinfo/Europe/London')
2021-11-11 15:00:00+00:00 tzfile('/usr/share/zoneinfo/Europe/London')
2021-12-11 15:00:00+00:00 tzfile('/usr/share/zoneinfo/Europe/London')
2022-01-11 15:00:00+00:00 tzfile('/usr/share/zoneinfo/Europe/London')
2022-02-11 15:00:00+00:00 tzfile('/usr/share/zoneinfo/Europe/London')
2022-03-11 15:00:00+00:00 tzfile('/usr/share/zoneinfo/Europe/London')
2022-04-11 15:00:00+01:00 tzfile('/usr/share/zoneinfo/Europe/London')
2022-05-11 15:00:00+01:00 tzfile('/usr/share/zoneinfo/Europe/London')
```

Is this happening with all the recurring events you have? If you can give me a .ics file with a sample VEVENT I'll see if I can reproduce it myself.

**Comment by eev2** [comment]
Hi Andrew.

Yes, it is happening with all events. I attach a sample ics file.
[calendar1.ics.txt](https://github.com/andrewramsay/ical_to_gcal_sync/files/6123844/calendar1.ics.txt)
This is how it is shown in my Google calendar (27 Match and 3 April):
![screen](https://user-images.githubusercontent.com/5764722/110806542-12ebdb00-827a-11eb-931b-29e46873942f.png)

**Comment by andrewramsay** [comment]
Thanks! Doing this:
```python
from datetime import date
from icalevents.icalevents import events
cal = events(file='calendar1.ics', end=date(2021, 12, 31))
for e in cal:
    print(e.start, e.start.tzinfo)
```

produces:

```
2021-03-13 09:00:00+00:00 tzutc()
2021-03-20 09:00:00+00:00 tzutc()
2021-03-27 09:00:00+00:00 tzutc()
2021-04-03 09:00:00+00:00 tzutc()
2021-04-10 09:00:00+00:00 tzutc()
2021-04-17 09:00:00+00:00 tzutc()
2021-04-24 09:00:00+00:00 tzutc()
```

which does not look right!

Your .ics file defines multiple timezones, and the DTSTART attribute on the event contains the time zone that it should be scheduled in, so I don't think there's anything wrong with the source data.

I'm thinking this is a problem with how icalevents handles calendars like yours. I don't know why they've implemented it like this, but if you look [here](https://github.com/irgangla/icalevents/blob/fee7f429b888b82946e34920a664a49397bd5f8c/icalevents/icalparser.py#L283) you can see it does parse the timezones from the file as you'd expect. Since there are multiple timezones in your file, it uses UTC as the timezone for the whole calendar. That's not a problem in itself, but then that UTC ```cal_tz``` object gets passed to [create_event](https://github.com/irgangla/icalevents/blob/fee7f429b888b82946e34920a664a49397bd5f8c/icalevents/icalparser.py#L297), where it is then used immediately [here](https://github.com/irgangla/icalevents/blob/fee7f429b888b82946e34920a664a49397bd5f8c/icalevents/icalparser.py#L163). So it effectively becomes a fixed timezone for every event. Since UTC obviously discards the DST adjustments that's what's causing your problem. 

The weird thing is that this seems to be very easy to fix by tweaking the icalevents code slightly. If I take the timezones dict from ```parse_events``` and pass it into ```create_event```, I can do something like this:

```python
# (ignoring error checking etc)
etz = component.get('dtstart').params 
# etz['TZID'] is the "GMT Standard Time" string embedded in DTSTART in the .ics file
tz = timezones[etz['TZID']] 
# now create the event with its own indicated timezone
event.start = normalize(component.get('dtstart').dt, tz=tz)
```

Now parsing your file again gives this:
```
2021-03-13 09:00:00+00:00 GMT Standard Time
2021-03-20 09:00:00+00:00 GMT Standard Time
2021-03-27 09:00:00+00:00 GMT Standard Time
2021-04-03 09:00:00+01:00 GMT Standard Time
2021-04-10 09:00:00+01:00 GMT Standard Time
2021-04-17 09:00:00+01:00 GMT Standard Time
2021-04-24 09:00:00+01:00 GMT Standard Time
```

which looks much more sensible. And finally if I run the ical_to_gcal_sync script with this tweak:

![cal](https://user-images.githubusercontent.com/9051013/110872658-22921080-82c8-11eb-91f9-a5b915605024.jpg)

If you want a quick fix this should work, but without digging further into icalevents I don't know if it might cause other problems elsewhere...

**Comment by eev2** [comment]
Thank you for the advice. If I understand you correctly, you are suggesting that I change the parse_events function to add the two lines that you indicated. Is there an easy way to do that?

It seems that this bug has been  [reported](https://github.com/irgangla/icalevents/issues/54) to icalevents.

For now, I am using the following workaround where I overwrite the time zone to my time zone. My knowledge of python is not great, so if you have a better way to do it, I would appreciate it.
```
from datetime import date
from icalevents.icalevents import events
from dateutil.tz import gettz

cal = events(file='calendar1.ics', end=date(2021, 12, 31))
for e in cal:
    print(e.start, e.start.tzinfo)

for i in range(len(cal)):
    cal[i].start = cal[i].start.replace(tzinfo=gettz('Europe/London'))
    cal[i].end = cal[i].end.replace(tzinfo=gettz('Europe/London'))

for e in cal:
    print(e.start, e.start.tzinfo)
```

**Comment by andrewramsay** [comment]
Here's a diff showing the minimal changes I made to the current master version of icalevents/icalparser.py, you could do the same to your local copy:

```diff
@@ -149,7 +149,7 @@ def encode(value: Optional[vText]) -> Optional[str]:
         return str(value.encode('utf-8'))

-def create_event(component, tz=UTC):
+def create_event(component, timezones, tz=UTC):
     """
     Create an event from its iCal representation.

@@ -160,6 +160,9 @@ def create_event(component, tz=UTC):

     event = Event()

+    params = component.get('dtstart').params
+    if params is not None and 'TZID' in params:
+        tz = timezones.get(params['TZID'], tz)
     event.start = normalize(component.get('dtstart').dt, tz=tz)

     if component.get('dtend'):
@@ -294,7 +297,7 @@ def parse_events(content, start=None, end=None, default_span=timedelta(days=7)):
     exceptions = {}
     for component in calendar.walk():
         if component.name == "VEVENT":
-            e = create_event(component, cal_tz)
+            e = create_event(component, timezones, cal_tz)

             if 'EXDATE' in component:
                 # Deal with the fact that sometimes it's a list and
```

So that's just passing ```timezones``` from ```parse_events``` into ```create_event``` as an extra parameter, and then pulling out the embedded timezone ID string and matching to a timezone where possible.

**Comment by eev2** [comment]
Thanks. I have applied these changes and I can confirm that it resolves the issue.
I hope that you can submit this to the icalevents project.

**Comment by andrewramsay** [comment]
Glad that fixed it! I'll try submitting a PR to icalevents at the weekend.
