### ISSUE TITLE
Max number of events?

### ISSUE THREAD

**Issue by sje30** [andrewramsay/ical_to_gcal_sync#4]
Hi, thanks for this software - I hope to use it for syncing my ics file to google.

Just checking though -- are there any limitations on the number of entries that will be synced?  I noticed this in the script:
```
   eventsResult = service.events().list(calendarId=CALENDAR_ID, timeMin=from_time, maxResults=100, singleEvents=True, orderBy='startTime', showDeleted=True).execute()
```

is there a hard limit of 100 events in the calendar?

**Comment by andrewramsay** [comment]
There shouldn't be any limits on numbers of events, but because I took some shortcuts writing the code then it could happen. The documentation for that method is [here](https://developers.google.com/resources/api-libraries/documentation/calendar/v3/python/latest/calendar_v3.events.html#list): 

> "maxResults: integer, Maximum number of events returned on one result page. The number of events in the resulting page may be less than this value, or none at all, even if there are more events matching the query. Incomplete pages can be detected by a non-empty nextPageToken field in the response. By default the value is 250 events. The page size can never be larger than 2500 events. Optional."

This script only retrieves upcoming events, and when I was writing it for myself I guess I picked 100 as a value for that parameter because I was sure I'd never have that many scheduled! And I clearly skimped on the logic/error handling too. The script should really be checking for incomplete pages and sending more requests until there are no more available, in which case the total number of events wouldn't matter. 

Anyway it seems like it should be pretty straightforward to fix, I might get a chance to do that in the next day or two (or feel free to do it yourself, happy to merge a PR!). A shorter term "fix" would be to increase 100 to something larger, just bear in mind the API docs state you may get incomplete results...

**Comment by andrewramsay** [comment]
Just committed a quick fix in c632bd0ba55281d1a4279917112aaed30df4c3ce that I think should take care of this - I tried running it with maxResults=2 and around 20 upcoming events, and it seems to handle the multiple pages of responses OK.

**Comment by sje30** [comment]
woah, thanks for the quick update.  I will pull and check.

**Comment by sje30** [comment]
thanks.  all working fine here!
