### ISSUE TITLE
Conference 

### ISSUE THREAD

**Issue by adambarnett52** [andrewramsay/ical_to_gcal_sync#5]
Hi, 
I am not great with python, but i have been looking at the code,...

is there a way to when added an event i can add a conference option? 
All events will have this same conference option ( zoom ) 

Thanks
Adam

**Comment by andrewramsay** [comment]
I'm not sure what you mean by "conference option", can you explain a little more? 

The thing is that all this script really does is take a list of iCal event objects and copy a few selected fields from them into Google Calendar event objects. If you just wanted to include another standard iCal field in this process, that would probably be a simple change. If you're talking about adding some feature that isn't already in the iCal spec, that's a bit outside the scope of this code! 

It's using the ics module for iCal support, so as a starting point I would suggest reading through [that module's documentation](https://icspy.readthedocs.io/en/stable/) and see if you can figure out if it supports what you want to do. If it does then that would make any changes much more straightforward.

**Comment by adambarnett52** [comment]
Hi, 

It would not be from the ICS, it would be a default field added to all events. I.e its the same for all events

Before adding the option it just says conference 

![Screenshot at 2019-10-24 15-23-27](https://user-images.githubusercontent.com/5599251/67495217-76b83880-f672-11e9-92dc-93d9de17dd15.png)

Then you can choose the option, i just have zoom in my drop down list![Screenshot at 2019-10-24 15-23-55](https://user-images.githubusercontent.com/5599251/67495262-859eeb00-f672-11e9-957c-722304d09335.png)

It just need to be the default option is selected

**Comment by andrewramsay** [comment]
Oh I see, you're talking about adding this field to the newly created *Google* calendar objects, and setting it to a default value?

From a quick skim of the Google Calendar API it seems like this should be possible, but it's kind of a niche use case! I'll have a better look at the API sometime this weekend, and if I can find a nice way to integrate it without affecting how the script currently operates then I'll add it in.

**Comment by adambarnett52** [comment]
that would be great, if you don't want to implement, i am happy to run a custom build

**Comment by andrewramsay** [comment]
OK, just spent 30 minutes looking at this, and unfortunately I think it will be problematic to implement. I don't typically use the conferencing field in my own events, so from my skimming of the API docs I thought it would be a case of requesting some sort of list of conferencing options from the user's account and copying one of them into new events. 

However I didn't realise until I checked today that to get the "Zoom Meeting" option actually requires installing a 3rd-party add-on for Google Calendar. Then you have to sign up for an account with Zoom  and link that to your calendar before you can add the "Zoom Meeting" option to an event. More importantly, when you add a "Zoom Meeting" to an event, it seems to trigger some communication with Zoom through the add-on in order to generate the unique meeting URL, passcode, and so on.

Unless I'm missing something this makes life much more complicated: instead of it being as simple as grabbing some data from the Calendar API and inserting it into new events, extra steps are now needed to manage the external communication with Zoom. They [do appear to have an API](https://marketplace.zoom.us/docs/api-reference/zoom-api) which looks like it will allow [new meeting info to be retrieved](https://marketplace.zoom.us/docs/api-reference/zoom-api/meetings/meetingcreate), but this seems way outside the very limited scope of this script.

If you're still interested in doing this, I don't think it'd be a ton of work to put together a script that allows you to create meetings with the Zoom API on-demand. Then you would need to figure out the mapping from the Zoom data fields to the various "conferenceData.*" fields listed in the [Calendar API](https://developers.google.com/calendar/v3/reference/events#resource-representations). At that point you could then just add a few lines to this script to create a new meeting & add details to [newly created events](https://github.com/andrewramsay/ical_to_gcal_sync/blob/321e03117ca2088213ca10e34c55ef1d7425b633/ical_to_gcal_sync.py#L240).

**Comment by adambarnett52** [comment]
Ok. Thanks for looking into this.

**Comment by adambarnett52** [comment]
Just to follow up in-case someone else wants to do something similar
If you put the zoom meeting url for the meeting room in the description of the event it will generated the meeting for you
